#!/bin/bash

export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export ftp_local_host=asprodftp
export datestamp=`date +%b%d%Y.%H%M`
export basename=Research_data
export data_file=${basename}.csv
export tag_file=${basename}.tag
export lz=research
export info_to="support@xyz.com,helpdesk@xyz.com"
export subject="Missing <name if file> name"
export ops=/opt/local/ops_scripts
export FileAge=30

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

# check for existence of file and email & abend if not found
        if [ ! -s $data_file ]; then
echo -e "\nexpected incoming file $data_file not found, sending email to SME team
and vendor NAME, Job will abend but no further action needed at this time\n"
cat $HOME/bin/mailbody.txt | Mail -s "$subject" $info_to
        exit 4
        fi

ftp_check $ftp_local_host

size_check $data_file

securezip $data_file inbound

echo -e "\ncreate tag file"
touch $tag_file

ftp_file $ftp_local_host $data_file $data_file "cd $lz" bin

ftp_file $ftp_local_host $tag_file $tag_file "cd $lz"

archive_clean $inbound_archive $data_file $FileAge

echo -e "\nclean up inbound directory"
rm -fv $data_file $tag_file
